-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME,  b.CATEGORY, SUM(b.PRICE * s.SALES) AS TOTAL_SALES
FROM BOOK as b
join AUTHOR as a
    on b.AUTHOR_ID = a.AUTHOR_ID
join BOOK_SALES as s
    on b.BOOK_ID = s.BOOK_ID
WHERE s.SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY a.AUTHOR_ID ASC,b.CATEGORY DESC