-- 코드를 입력하세요
SELECT DISTINCT p.PRODUCT_CODE, SUM(p.PRICE*o.SALES_AMOUNT) as SALES
FROM PRODUCT as p
join OFFLINE_SALE as o
    on p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC
